# Generated by Django 5.0.3 on 2024-10-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='city',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='farmer',
            name='state',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
