# Generated by Django 5.0.3 on 2024-10-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_farmer_city_farmer_state_alter_farmer_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='location',
        ),
        migrations.AddField(
            model_name='farmer',
            name='district',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='interests',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
    ]
