# Generated by Django 5.0.3 on 2024-10-24 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_croprecommendation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CropRecommendation',
        ),
    ]
