# Generated by Django 5.0.3 on 2024-10-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_croprecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
