# Generated by Django 5.0.3 on 2024-10-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measurement',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('litre', 'Litres'), ('dozen', 'Dozen')], default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='quality',
            field=models.CharField(choices=[('poor', 'Poor'), ('good', 'Good'), ('great', 'Great')], max_length=10),
        ),
    ]
