# Generated by Django 5.0.3 on 2024-10-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_product_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='product',
            name='measurement',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('l', 'Liters'), ('dozen', 'Dozen')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='quality',
            field=models.CharField(choices=[('poor', 'Poor'), ('good', 'Good'), ('best', 'Best')], max_length=10),
        ),
    ]
