# Generated by Django 5.0.3 on 2024-10-26 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_product_measurement_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('gm', 'Grams')], default='kg', max_length=10),
        ),
    ]
